disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Nick Moyer | Platform Engineer"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "logo_dark.png"
secondaryLogo = "logo_light.png"

[params.author]
name = "Nick Moyer"
image = "profile.png"
headline = "Senior Platform Engineer @ [Serif Health](https://www.serifhealth.com)"
bio = "Senior Platform Engineer passionate about architecting scalable backends, AI-driven automation, and turning complex data into real-world utility."
links = [
    { github = "https://github.com/nick-moyer" },
    { linkedin = "https://www.linkedin.com/in/npmoyer" },
    { bluesky = "https://bsky.app/profile/nickmoyer.dev" },
    { goodreads = "https://www.goodreads.com/nick-moyer" },
    { email = "mailto:hello@nickmoyer.dev" },
]